(() => {
  // <stdin>
  console.log("This site was generated by Hugo.");
  document.getElementById("btncomic").addEventListener("click", function() {
    const menu = document.getElementById("menucomic");
    if (menu.classList.contains("hidden")) {
      menu.classList.remove("hidden");
      menu.classList.add("flex");
    } else {
      menu.classList.remove("flex");
      menu.classList.add("hidden");
    }
  });
  document.getElementById("btnanimation").addEventListener("click", function() {
    const menu = document.getElementById("menuanimation");
    if (menu.classList.contains("hidden")) {
      menu.classList.remove("hidden");
      menu.classList.add("flex");
    } else {
      menu.classList.remove("flex");
      menu.classList.add("hidden");
    }
  });
  document.getElementById("btnmusic").addEventListener("click", function() {
    const menu = document.getElementById("menumusic");
    if (menu.classList.contains("hidden")) {
      menu.classList.remove("hidden");
      menu.classList.add("flex");
    } else {
      menu.classList.remove("flex");
      menu.classList.add("hidden");
    }
  });
  document.getElementById("btn-comic").addEventListener("click", function() {
    document.getElementById("btn-comic").classList.add("hidden");
  });
})();
